layout_spectrum: 0.7424812
typography_spectrum: 0.8865915
color:
  saturation: 0.9961564
  brandStrength: 0.4327056
  lightness: 0.8997494
  brandColors:
    - '#FFFFFF'
    - '#302C29'
    - '#090907'
    - '#63605B'
    - '#BAB5AF'
  rhythmicContrast: 0.2612782
name: Sedonaweddingflowers
