layout_spectrum: 0.3317493
color:
  saturation: 0.9961564
  brandStrength: 0.4327056
  lightness: 0.8997494
  rhythmicContrast: 0.2612782
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.703904
name: Sedonaweddingflowers
