collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8865915
color:
  saturation: 1
  brandStrength: 0.4327056
  lightness: 0.8289474
  brandColors:
    - '#FFFFFF'
    - '#302C29'
    - '#090907'
    - '#63605B'
    - '#BAB5AF'
  rhythmicContrast: 0.2612782
layout_spectrum: 0.7424812
name: Sedonaweddingflowers
